sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t priyankpuri/docker-try -f Dockerfile.dev .

script:
  - docker run -e CI=true priyankpuri/docker-try npm run test