sudo: required
services:
  - docker

language: generic 

before_install:
  - docker build -t priyankpuri/docker-try -f Dockerfile.dev .

  script:
    - docker run priyankpuri/docker-try npm run test -- --coverage